// <auto-generated />
using System;
using Inovait.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inovait.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InovaitDbContext))]
    partial class InovaitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inovait.Core.Domain.Academics.ClassGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_ClassGroup");

                    b.HasAlternateKey("Id", "AcademicYearId")
                        .HasName("UQ_ClassGroup_Id_AcademicYear_ForEnrollment");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("IX_ClassGroup_GradeId");

                    b.HasIndex("AcademicYearId", "GradeId", "SchoolId")
                        .HasDatabaseName("IX_ClassGroup_AcademicYearId_GradeId_SchoolId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AcademicYearId", "GradeId", "SchoolId"), new[] { "Code" });

                    b.HasIndex("SchoolId", "AcademicYearId", "GradeId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_ClassGroup_Context");

                    b.ToTable("ClassGroup", "academic", t =>
                        {
                            t.HasCheckConstraint("CK_ClassGroup_Code_NotBlank", "LEN(TRIM([Code])) > 0");

                            t.HasCheckConstraint("CK_ClassGroup_UpdatedAtUtc", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("Inovait.Core.Domain.Academics.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int");

                    b.Property<int>("ClassGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("StudentPersonId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Enrollment");

                    b.HasIndex("ClassGroupId", "AcademicYearId");

                    b.HasIndex("ClassGroupId", "StudentPersonId")
                        .HasDatabaseName("IX_Enrollment_ClassGroupId_StudentPersonId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ClassGroupId", "StudentPersonId"), new[] { "AcademicYearId", "CreatedAtUtc" });

                    b.HasIndex("StudentPersonId", "AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Enrollment_StudentPersonId_AcademicYearId");

                    b.ToTable("Enrollment", "academic");
                });

            modelBuilder.Entity("Inovait.Core.Domain.Catalogs.AcademicConfiguration", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<int>("CurrentAcademicYearId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_AcademicConfiguration");

                    b.HasIndex("CurrentAcademicYearId");

                    b.ToTable("AcademicConfiguration", "catalog", t =>
                        {
                            t.HasTrigger("TR_AcademicConfiguration_PreventDelete");

                            t.HasCheckConstraint("CK_AcademicConfiguration_Singleton", "[Id] = 1");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            CurrentAcademicYearId = 1
                        });
                });

            modelBuilder.Entity("Inovait.Core.Domain.Catalogs.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_AcademicYear");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_AcademicYear_Code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_AcademicYear_Name");

                    b.ToTable("AcademicYear", "catalog", t =>
                        {
                            t.HasTrigger("TR_AcademicYear_ProtectCode");

                            t.HasCheckConstraint("CK_AcademicYear_Code_NotBlank", "LEN(TRIM([Code])) > 0");

                            t.HasCheckConstraint("CK_AcademicYear_DateRange", "[EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_AcademicYear_Name_NotBlank", "LEN(TRIM([Name])) > 0");

                            t.HasCheckConstraint("CK_AcademicYear_UpdatedAtUtc", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AY-2026",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndDate = new DateOnly(2026, 12, 31),
                            Name = "Academic Year 2026",
                            StartDate = new DateOnly(2026, 1, 1),
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Inovait.Core.Domain.Catalogs.DocumentType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_DocumentType");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_DocumentType_Code");

                    b.ToTable("DocumentType", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_DocumentType_Code_NotBlank", "LEN(TRIM([Code])) > 0");

                            t.HasCheckConstraint("CK_DocumentType_Name_NotBlank", "LEN(TRIM([Name])) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "CC",
                            IsActive = true,
                            Name = "Citizenship Card"
                        });
                });

            modelBuilder.Entity("Inovait.Core.Domain.Catalogs.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_Grade");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_Grade_Code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Grade_Name");

                    b.HasIndex("SortOrder")
                        .IsUnique()
                        .HasDatabaseName("UQ_Grade_SortOrder");

                    b.ToTable("Grade", "catalog", t =>
                        {
                            t.HasTrigger("TR_Grade_ProtectCode");

                            t.HasCheckConstraint("CK_Grade_Code_NotBlank", "LEN(TRIM([Code])) > 0");

                            t.HasCheckConstraint("CK_Grade_Name_NotBlank", "LEN(TRIM([Name])) > 0");

                            t.HasCheckConstraint("CK_Grade_SortOrder", "[SortOrder] > 0");

                            t.HasCheckConstraint("CK_Grade_UpdatedAtUtc", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "G01",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "First Grade",
                            SortOrder = (short)1,
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Inovait.Core.Domain.Catalogs.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_School");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_School_Code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_School_Name");

                    b.ToTable("School", "catalog", t =>
                        {
                            t.HasTrigger("TR_School_ProtectStableValues");

                            t.HasCheckConstraint("CK_School_Code_NotBlank", "LEN(TRIM([Code])) > 0");

                            t.HasCheckConstraint("CK_School_Name_NotBlank", "LEN(TRIM([Name])) > 0");

                            t.HasCheckConstraint("CK_School_Sector", "[Sector] IN ('Public','Private')");

                            t.HasCheckConstraint("CK_School_Sector_NotBlank", "LEN(TRIM([Sector])) > 0");

                            t.HasCheckConstraint("CK_School_UpdatedAtUtc", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "SCH-001",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "North Learning Center",
                            Sector = "Public",
                            UpdatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Inovait.Core.Domain.People.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<short>("DocumentTypeId")
                        .HasColumnType("smallint");

                    b.Property<string>("FirstNames")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("LastNames")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_Person");

                    b.HasIndex("DocumentTypeId", "DocumentNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Person_DocumentTypeId_DocumentNumber");

                    b.HasIndex("LastNames", "FirstNames", "Id")
                        .HasDatabaseName("IX_Person_LastNames_FirstNames_Id");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("LastNames", "FirstNames", "Id"), new[] { "DocumentTypeId", "DocumentNumber", "BirthDate" });

                    b.ToTable("Person", "people", t =>
                        {
                            t.HasCheckConstraint("CK_Person_DocumentNumber_NotBlank", "LEN(TRIM([DocumentNumber])) > 0");

                            t.HasCheckConstraint("CK_Person_FirstNames_NotBlank", "LEN(TRIM([FirstNames])) > 0");

                            t.HasCheckConstraint("CK_Person_LastNames_NotBlank", "LEN(TRIM([LastNames])) > 0");

                            t.HasCheckConstraint("CK_Person_UpdatedAtUtc", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("Inovait.Core.Domain.People.Student", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonId")
                        .HasName("PK_Student");

                    b.ToTable("Student", "people");
                });

            modelBuilder.Entity("Inovait.Core.Domain.People.Teacher", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("PersonId")
                        .HasName("PK_Teacher");

                    b.ToTable("Teacher", "people", t =>
                        {
                            t.HasCheckConstraint("CK_Teacher_UpdatedAtUtc", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("Inovait.Core.Domain.Staff.TeacherContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CancellationEffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("TeacherPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id")
                        .HasName("PK_TeacherContract");

                    b.HasIndex("SchoolId", "StartDate", "EndDate")
                        .HasDatabaseName("IX_TeacherContract_SchoolId_StartDate_EndDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SchoolId", "StartDate", "EndDate"), new[] { "TeacherPersonId", "Status", "CancellationEffectiveDate" });

                    b.HasIndex("TeacherPersonId", "StartDate", "EndDate")
                        .HasDatabaseName("IX_TeacherContract_TeacherPersonId_StartDate_EndDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("TeacherPersonId", "StartDate", "EndDate"), new[] { "SchoolId", "Status", "CancelledAtUtc", "CancellationReason", "CancellationEffectiveDate" });

                    b.HasIndex("TeacherPersonId", "SchoolId", "StartDate", "EndDate")
                        .IsUnique()
                        .HasDatabaseName("UQ_TeacherContract_Exact");

                    b.ToTable("TeacherContract", "staff", t =>
                        {
                            t.HasCheckConstraint("CK_TeacherContract_CancellationEffectiveDate", "[CancellationEffectiveDate] IS NULL OR ([CancellationEffectiveDate] >= [StartDate] AND ([EndDate] IS NULL OR [CancellationEffectiveDate] <= [EndDate]))");

                            t.HasCheckConstraint("CK_TeacherContract_CancellationReason_NotBlank", "[CancellationReason] IS NULL OR LEN(TRIM([CancellationReason])) > 0");

                            t.HasCheckConstraint("CK_TeacherContract_DateRange", "[EndDate] IS NULL OR [EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_TeacherContract_Status", "[Status] IN ('Confirmed','Cancelled')");

                            t.HasCheckConstraint("CK_TeacherContract_StatusCancellation", "([Status]='Confirmed' AND [CancelledAtUtc] IS NULL AND [CancellationReason] IS NULL AND [CancellationEffectiveDate] IS NULL) OR ([Status]='Cancelled' AND [CancelledAtUtc] IS NOT NULL AND [CancellationReason] IS NOT NULL AND [CancellationEffectiveDate] IS NOT NULL)");

                            t.HasCheckConstraint("CK_TeacherContract_Status_NotBlank", "LEN(TRIM([Status])) > 0");

                            t.HasCheckConstraint("CK_TeacherContract_UpdatedAtUtc", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("Inovait.Core.Domain.Academics.ClassGroup", b =>
                {
                    b.HasOne("Inovait.Core.Domain.Catalogs.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ClassGroup_AcademicYear");

                    b.HasOne("Inovait.Core.Domain.Catalogs.Grade", null)
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ClassGroup_Grade");

                    b.HasOne("Inovait.Core.Domain.Catalogs.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_ClassGroup_School");
                });

            modelBuilder.Entity("Inovait.Core.Domain.Academics.Enrollment", b =>
                {
                    b.HasOne("Inovait.Core.Domain.People.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentPersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Enrollment_Student");

                    b.HasOne("Inovait.Core.Domain.Academics.ClassGroup", null)
                        .WithMany()
                        .HasForeignKey("ClassGroupId", "AcademicYearId")
                        .HasPrincipalKey("Id", "AcademicYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Enrollment_ClassGroupId_AcademicYearId");
                });

            modelBuilder.Entity("Inovait.Core.Domain.Catalogs.AcademicConfiguration", b =>
                {
                    b.HasOne("Inovait.Core.Domain.Catalogs.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("CurrentAcademicYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_AcademicConfiguration_AcademicYear");
                });

            modelBuilder.Entity("Inovait.Core.Domain.People.Person", b =>
                {
                    b.HasOne("Inovait.Core.Domain.Catalogs.DocumentType", null)
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Person_DocumentType");
                });

            modelBuilder.Entity("Inovait.Core.Domain.People.Student", b =>
                {
                    b.HasOne("Inovait.Core.Domain.People.Person", null)
                        .WithOne()
                        .HasForeignKey("Inovait.Core.Domain.People.Student", "PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Student_Person");
                });

            modelBuilder.Entity("Inovait.Core.Domain.People.Teacher", b =>
                {
                    b.HasOne("Inovait.Core.Domain.People.Person", null)
                        .WithOne()
                        .HasForeignKey("Inovait.Core.Domain.People.Teacher", "PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Teacher_Person");
                });

            modelBuilder.Entity("Inovait.Core.Domain.Staff.TeacherContract", b =>
                {
                    b.HasOne("Inovait.Core.Domain.Catalogs.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TeacherContract_School");

                    b.HasOne("Inovait.Core.Domain.People.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherPersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TeacherContract_Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
